### ISSUE TITLE
Gamecube Logo not Shown in Platform List

### ISSUE THREAD

**Issue by jusuchin85** [RobZombie9043/COLORFUL#1]
I've just tried the theme, and noticed that all logos and videos loaded — except for GameCube.

Attached video showing this:

https://github.com/RobZombie9043/COLORFUL/assets/1155821/d933b2a0-c1ea-4fbf-b687-18eebab9a54f

**Comment by RobZombie9043** [comment]
There are some images and videos sources that are directly referencing the collection shortnames and looking for corresponding filename in the image/video asset folders. 
I have my gamecube collection shortname set as "gamecube" and it works but I'm guessing yours is called "gc" or something else.

I'll see if I can add these to the alias functions to look up different common combinations for each system which should make it less rigid to set up.

Thanks for reporting this.

**Comment by RobZombie9043** [comment]
Updated the collections video and image source references to check against common platform shortname aliases to be less dependant on following the exact naming convention.

Specifically GameCube should now work with shortname set to any of the following: gamecube, gc, nintendo gamecube
