### ISSUE TITLE
Dynamically Change the Button Prompts

### ISSUE THREAD

**Issue by jusuchin85** [RobZombie9043/COLORFUL#2]
Currently, the button to access the game list from the platform list is set to `A`.

Would it be possible for this to be dynamic? On my Odin 2, I press `B` to access the game list.

**Comment by RobZombie9043** [comment]
Yep that is easy enough, will add it in when I get a chance

**Comment by RobZombie9043** [comment]
Added Accept Button options for A, B, cross (X) and circle (O) covering Xbox/Nintendo/PS layouts and regional variations
